---
- name: Pull data
  block:
    - name: Pull files using rsync
      become: yes
      ansible.posix.synchronize:
        src: '{{ item.value.path }}'
        dest: "{{ [playbook_dir, 'data'] | path_join }}"
        delete: true
        mode: pull
      loop: '{{ data_dirs | dict2items }}'
      when: item.value.pull
  when: data_pull
